apiVersion: v1
kind: ConfigMap
metadata:
  name: "jenkins-x-pod-templates"
data:
{{- if .Values.jenkins.Agent.Enabled }}
{{- $agent := .Values.jenkins.Agent -}}
{{- $globalenv := .Values.jenkins.Servers.Global.EnvVars -}}
{{- range $pkey, $pval := .Values.jenkins.Agent.PodTemplates }}
  {{ $pval.Name }}: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: {{ $pval.Label }}
      labels:
        jenkins.io/kind: build-pod
      annotations:
        jenkins-x.io/devpodPorts: {{ $pval.DevPodPorts }}
    spec:
{{- if $pval.ServiceAccount }}
      serviceAccount: {{ $pval.ServiceAccount }}
{{- end }}
      nodeSelector:
{{- range $key, $value := $pval.NodeSelector }}
        {{- $key }}: {{ $value }}
{{- end }}
      volumes:
      - name: workspace-volume
        emptyDir: {}
{{- if $agent.DockerHostPath }}
      - name: docker-daemon
        hostPath:
          path: {{ $agent.DockerHostPath }}
{{- end }}
      {{ $pval.volumes | toYaml | indent 6 | trim }}
      containers:
  {{- range $ckey, $cval := $pval.Containers }}
  {{- if ne "Jnlp" $ckey }}
      - name: {{ $ckey | lower }}
        image: {{ $cval.Image }}
        args:
        - cat
        command:
        - /bin/sh
        - -c
        workingDir: /home/jenkins
        securityContext:
          privileged: {{ default false $cval.Privileged }}
  {{- if $cval.AlwaysPullImage }}
        imagePullPolicy: Always
  {{- end }}
        tty: {{ default false $cval.Tty }}
        env:
        - name: DOCKER_REGISTRY
          valueFrom:
            configMapKeyRef:
              name: jenkins-x-docker-registry
              key: docker.registry
        - name: TILLER_NAMESPACE
          value: {{ $globalenv.TILLER_NAMESPACE }}
  {{- range $ekey, $eval := $pval.EnvVars }}
        - name: {{ $ekey }}
          value: {{ $eval }}
  {{- end }}
        resources:
          requests:
            cpu: {{ $cval.RequestCpu }}
            memory: {{ $cval.RequestMemory }}
          limits:
  {{- if $pval.LimitCpu }}
            cpu: {{ $cval.LimitCpu }}
  {{- end }}
  {{- if $pval.LimitMemory }}
            memory: {{ $cval.LimitMemory }}
  {{- end }}
        volumeMounts:
          - name: workspace-volume
          - mountPath: /home/jenkins
  {{- if $agent.DockerHostPath }}
          - name: docker-daemon
            mountPath: {{ $agent.DockerMountPath }}
  {{- end }}
  {{- if $cval.volumeMounts }}
          {{ $cval.volumeMounts | toYaml | indent 10 | trim }}
  {{- end }}
  {{- end }}
{{- end }}
{{- if $pval.ImagePullSecret }}
      imagePullSecrets:
        - name: {{ $pval.ImagePullSecret }}
{{- end }}
{{- end }}
{{- end -}}
